Update README.md for Helm Chart Link
rancher/turtles pull request #552
Opened 2024-05-24 15:16 UTC by inichols

**What this PR does / why we need it**:

Installation & Usage is pointing to a broken page for deployed as a Helm Chart. Believe this is the page that is meant to be linked

2024-05-27 09:55 UTC, salasberryfin requested changes
Hi @inichols, thanks for reporting this issue. Since we consider the installation via Rancher Dashboard as preferred alternative, I'd say we should point this link to the [Install Rancher Turtles](https://turtles.docs.rancher.com/category/install-rancher-turtles) homepage, which includes links for both alternatives: via UI and via terminal. What do you think?

2024-05-27 09:55 UTC, salasberryfin commented on README.md
> +Rancher Turtles is deployed using a Helm Chart. For instructions, see the [getting started guide](https://turtles.docs.rancher.com/getting-started/install-rancher-turtles/using_helm).
```suggestion
Rancher Turtles is deployed using a Helm Chart. For instructions, see the [installation guide](https://turtles.docs.rancher.com/category/install-rancher-turtles).
```

2024-06-03 07:41 UTC, furkatgofurov7 commented
@inichols hey, thanks for the PR! Can you resolve the comment from @salasberryfin please, so we can take this PR in?

2024-07-30 07:49 UTC, furkatgofurov7 commented
Duplicate of #602

2024-07-30 07:49 UTC, closed without merging